### PR TITLE
Skip dependency caches path in `_findRoots`.

### LINKED ISSUE #268: custom_lint fails with "Failed to decode" on unrelated files.
**Describe the bug**
When trying to run custom_lint on a more complex flutter project, it fails with `Failed to decode .dart_tool/package_config.json` on unrelated files. This happens for:
- Symlinked iOS plugins (when depending on a package that provides a native iOS flutter plugin, i. e. `package_info_plus`
  - `Failed to decode .dart_tool/package_config.json at .../ios/.symlinks/plugins/package_info_plus. Make sure to run pub get first.`
- The synthetic package generated by `flutter_localizations`
  - `Failed to decode .dart_tool/package_config.json at .../.dart_tool/flutter_gen. Make sure to run pub get first.`

The error is the same in all cases (with different paths):
```
PathNotFoundException: Cannot open file, path = '.../.dart_tool/package_config.json' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
#5      parsePackageConfig (package:custom_lint_core/src/package_utils.dart:161:5)
<asynchronous suspension>
#6      CustomLintProject.parse (package:custom_lint/src/workspace.dart:1025:34)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#8      CustomLintWorkspace.fromContextRoots (package:custom_lint/src/workspace.dart:516:22)
<asynchronous suspension>
#9      _runServer.<anonymous closure> (package:custom_lint/custom_lint.dart:90:25)
<asynchronous suspension>
#10     _AsyncCompleter.complete (dart:async/future_impl.dart:41:3)
<asynchronous suspension>
#11     _runServer.<anonymous closure> (package:custom_lint/custom_lint.dart:126:19)
<asynchronous suspension>
#12     _runServer (package:custom_lint/custom_lint.dart:86:3)
<asynchronous suspension>
#13     customLint (package:custom_lint/custom_lint.dart:50:5)
<asynchronous suspension>
#14     entrypoint (file:///Users/user/.pub-cache/hosted/pub.dev/custom_lint-0.6.5/bin/custom_lint.dart:68:3)
<asynchronous suspension>
#15     main (file:///Users/user/.pub-cache/hosted/pub.dev/custom_lint-0.6.5/bin/custom_lint.dart:80:5)
<asynchronous suspension>

#0      CustomLintProject.parse.<anonymous closure> (package:custom_lint/src/workspace.dart:1028:7)
#1      _rootRunBinary (dart:async/zone.dart:1423:47)
#2      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:178:22)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:894:13)
#6      Future._completeError (dart:async/future_impl.dart:674:5)
<asynchronous suspension>
```

**To Reproduce**
(Example project: [test_project.zip](https://github.com/user-attachments/files/16656145/test_project.zip))
- `flutter create -e test_project`
- `flutter pub add package_info_plus 'flutter_localizations:{"sdk":"flutter"}' dev:custom_lint`
- Setup `custom_lint` and `flutter_localizations`
- `flutter build ios --debug --no-codesign` (To create the `.symlinks` directory)
- Run `custom_lint`

**Expected behavior**
The tool should run without any errors.

**Workaround**
For now, the only workaround seems to be to delete the `ios/.symlinks` and `.dart_tool/flutter_gen` directories prior to executing `dart run custom_lint`.

### PR DESCRIPTION
**Pull request by Kurogoma4D**
Fixes #268.

### CODE REVIEW

File: packages/custom_lint/lib/src/workspace.dart [hunk 1]
```diff
@@ -424,6 +424,11 @@ Iterable<String> _findRoots(String path) sync* {
   final directory = Directory(path);
 
   yield* directory.listSync(recursive: true).whereType<File>().where((file) {
+    // Skip the root of dependency caches.
+    if (file.path.contains('.dart_tool') || file.path.contains('.symlinks')) {
```
Comment (rrousselGit) [inline packages/custom_lint/lib/src/workspace.dart:428]: That's valuable, but this isn't the right fix. We should instead ignore pubspecs without a package_config.json

Comment (Kurogoma4D) [reply packages/custom_lint/lib/src/workspace.dart]: So, is this change correct? https://github.com/invertase/dart_custom_lint/pull/269/commits/fd024f6a8849113789bcf793cba3c870785cc616
(I thought that maybe we should check it after return `_findRoots`.)

**Comment by rrousselGit** [comment]
Looking good. Do you mind adding a test?

**Comment by Kurogoma4D** [comment]
@rrousselGit 
While adding the test, I noticed the current code is not sufficient for a multi-package project like [this case](https://github.com/invertase/dart_custom_lint/blob/main/packages/custom_lint/test/cli_process_test.dart#L229).
I still think we should check the contextRoot path which nests `.dart_tool` and `.symlinks`, but how about it?

**Comment by rrousselGit** [comment]
Sure. As I said, ignoring those is valuable. Just make sure to test everything :)

File: packages/custom_lint/lib/src/workspace.dart [hunk 2]
```diff
@@ -429,8 +429,14 @@ Iterable<String> _findRoots(String path) sync* {
       return false;
     }
     // Check if the project has a package_config.json file.
-    return File(join(file.parent.path, '.dart_tool/package_config.json'))
-        .existsSync();
+    final isChildFromCache =
+        file.path.contains('.dart_tool') || file.path.contains('.symlinks');
```
Comment (rrousselGit) [inline packages/custom_lint/lib/src/workspace.dart:433]: fwiw it's not safe to use `.contains`.
This would make against things like `path/foo.dart_tool` or `.dart_toolwhatever`

We should be using file.uri.segments.any

File: packages/custom_lint/lib/src/workspace.dart [hunk 3]
```diff
@@ -429,8 +429,14 @@ Iterable<String> _findRoots(String path) sync* {
...
+    if (isChildFromCache) {
+      return File(join(file.parent.path, '.dart_tool/package_config.json'))
```
Comment (rrousselGit) [inline packages/custom_lint/lib/src/workspace.dart:435]:
```suggestion
      return file.parent.packageConfig
```

**Comment by Kurogoma4D** [comment]
@rrousselGit I'm sorry to rush you, but could you review again?
This blocks some project's CI using custom_lint.

**Comment by woteska** [comment]
@rrousselGit @Kurogoma4D guys thanks for the work.
We are also waiting for this fix, can you estimate when it can be published? It breaks our git hooks.
