### PR TITLE
Fix TypeChecker.isSuperTypeOf throws on null value

### LINKED ISSUE #229: TypeChecker.isSuperTypeOf throws on null value
**Describe the bug**

`TypeChecker.isSuperTypeOf` throws when `staticType.element` is null. 

```dart
bool isSuperTypeOf(DartType staticType) => isSuperOf(staticType.element!);
```

**To Reproduce**

```dart
void fn((int, String) record) {
  final first = record.$1;
}

context.registry.addPropertyAccess((node) {
  final targetType = node.realTarget.staticType;
  if (targetType == null) return;
  print(targetType.element); // null
  someTypeChecker.isSuperTypeOf(targetType); // Throws
});
```

**Expected behavior**

`TypeChecker.isSuperTypeOf` should behave like `TypeChecker.isAssignableFromType`, which returns false when `staticType.element` is null.

### PR DESCRIPTION
**Pull request by charlescyt**
Close #229

### CODE REVIEW

File: packages/custom_lint_core/lib/src/type_checker.dart [hunk 1]
```diff
@@ -221,7 +221,10 @@ abstract class TypeChecker {
   ///
   /// This only takes into account the *extends* hierarchy. If you wish
   /// to check mixins and interfaces, use [isAssignableFromType].
-  bool isSuperTypeOf(DartType staticType) => isSuperOf(staticType.element!);
+  bool isSuperTypeOf(DartType staticType) {
+    final element = staticType.element;
```
Comment (rrousselGit) [inline packages/custom_lint_core/lib/src/type_checker.dart:225]: Could you add a check here? https://github.com/invertase/dart_custom_lint/blob/main/packages/custom_lint_core/test/type_checker_test.dart

File: packages/custom_lint_core/lib/src/type_checker.dart [hunk 2]
```diff
@@ -221,7 +221,10 @@ abstract class TypeChecker {
   ///
   /// This only takes into account the *extends* hierarchy. If you wish
   /// to check mixins and interfaces, use [isAssignableFromType].
-  bool isSuperTypeOf(DartType staticType) => isSuperOf(staticType.element!);
+  bool isSuperTypeOf(DartType staticType) {
```
Comment (rrousselGit) [inline packages/custom_lint_core/lib/src/type_checker.dart:224]:
```suggestion
  // TODO changelog patch: Fixed a bug where isSuperTypeOf throws if the element is null (thanks to @charlescyt)
  bool isSuperTypeOf(DartType staticType) {
```

File: packages/custom_lint_core/lib/src/type_checker.dart (hunk 1 above)
Comment (charlescyt) [reply packages/custom_lint_core/lib/src/type_checker.dart:226]: Sure!

File: packages/custom_lint_core/test/type_checker_test.dart [hunk 3]
```diff
@@ -34,6 +34,31 @@ void main() {
...
+
+    const checker = TypeChecker.fromName('record');
+
+    unit.unit.accept(
+      _PropertyAccessVisitor((node) {
+        expect(node.realTarget.staticType!.element, isNull);
+        expect(
+          checker.isExactlyType(node.realTarget.staticType!),
+          isFalse,
+        );
```
Comment (rrousselGit) [inline packages/custom_lint_core/test/type_checker_test.dart:57]: Could you move this out of the callback?

I'd want to avoid the case where no `node` are found and the test is silently passing

Comment (charlescyt) [reply packages/custom_lint_core/test/type_checker_test.dart:57]: Should I add the below check? 
```dart
expect(propertyAccessNode, isNotNull);
```

File: packages/custom_lint_core/test/type_checker_test.dart [hunk 4]
```diff
@@ -34,6 +34,34 @@ void main() {
...
+''');
+
+    final unit = await resolveFile2(path: file.path);
+    unit as ResolvedUnitResult;
+
+    const checker = TypeChecker.fromName('record');
+
+    PropertyAccess? propertyAccessNode;
+
+    unit.unit.accept(
```
Comment (rrousselGit) [inline packages/custom_lint_core/test/type_checker_test.dart:51]:
```suggestion
    late final PropertyAccess? propertyAccessNode;
    unit.unit.accept(
```

File: packages/custom_lint_core/test/type_checker_test.dart [hunk 5]
```diff
@@ -34,6 +34,34 @@ void main() {
...
+      _PropertyAccessVisitor((node) {
+        propertyAccessNode = node;
+      }),
+    );
+
+    expect(propertyAccessNode, isNotNull);
+    expect(propertyAccessNode!.realTarget.staticType!.element, isNull);
```
Comment (rrousselGit) [inline packages/custom_lint_core/test/type_checker_test.dart:58]:
```suggestion
    expect(propertyAccessNode.realTarget.staticType!.element, isNull);
```

File: packages/custom_lint_core/test/type_checker_test.dart [hunk 6]
```diff
@@ -34,6 +34,34 @@ void main() {
...
+    expect(
+      checker.isExactlyType(propertyAccessNode!.realTarget.staticType!),
```
Comment (rrousselGit) [inline packages/custom_lint_core/test/type_checker_test.dart:60]:
```suggestion
      checker.isExactlyType(propertyAccessNode.realTarget.staticType!),
```

**Comment by rrousselGit** [comment]
LGTM, thanks!
